packages:
  - frontend
  - server

catalog:
  '@antfu/eslint-config': ^5.0.0
  '@iconify-json/carbon': ^1.2.11
  '@types/node': ^24.1.0
  '@unocss/eslint-plugin': ^66.3.3
  '@vitejs/plugin-vue': ^6.0.1
  '@vue-macros/volar': ^0.30.15
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^13.6.0
  eslint: ^9.32.0
  eslint-plugin-format: ^1.0.1
  jsdom: ^26.1.0
  lint-staged: ^16.1.2
  simple-git-hooks: ^2.13.0
  taze: ^19.1.0
  typescript: ^5.8.3
  unocss: ^66.3.3
  unplugin-auto-import: ^19.3.0
  unplugin-vue-components: ^28.8.0
  unplugin-vue-macros: ^2.14.5
  unplugin-vue-router: ^0.14.0
  vite: ^7.0.6
  vitest: ^3.2.4
  vue: ^3.5.18
  vue-router: ^4.5.1
  vue-tsc: ^3.0.4
